---
- name: Restart remote_syslog
  service: name=remote_syslog state=restarted
  when: papertrail_enabled

- name: Restart Rsyslog
  service: name=rsyslog state=restarted
  when: papertrail_rsyslog_enabled
